# -*- coding: utf-8 -*-
"""Diabetic_data Machine Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2OFmlZnAvCvJw_FZlnxtT6cZhOJ1QDR

# 🏥 Projet de Machine Learning – Analyse et Prédiction du Diabète

## 📌 Introduction Générale

Le diabète est une maladie chronique qui constitue un enjeu majeur de santé publique dans le monde. Une détection précoce et un suivi médical efficace permettent de réduire les complications graves ainsi que les coûts hospitaliers.

Dans ce projet, nous appliquons des techniques de Machine Learning sur deux jeux de données réels afin d’étudier deux problématiques complémentaires liées au diabète.

---

## 🎯 Objectif Global du Projet

L’objectif principal est d’utiliser des modèles de Machine Learning pour :

- Détecter la présence du diabète chez un patient à partir de données médicales.
- Prédire la réadmission hospitalière des patients diabétiques.

Le projet suit les étapes fondamentales d’un processus de Data Science :

1. Business Understanding  
2. Data Understanding (Analyse Exploratoire des Données)  
3. Data Preparation  
4. Modeling  
5. Évaluation des modèles  

---

# 📁 Description des Jeux de Données

Ce projet utilise deux jeux de données liés au diabète afin de traiter deux problématiques différentes en Machine Learning.

---

## 🔵 1️⃣ Dataset : Pima Indians Diabetes Database

Ce dataset contient des données médicales de patientes adultes utilisées pour la détection du diabète.

### 📌 Objectif du dataset
Prédire si une personne est atteinte de diabète ou non.

### 📊 Variables principales
- Pregnancies (nombre de grossesses)
- Glucose (niveau de glucose)
- BloodPressure (pression artérielle)
- SkinThickness (épaisseur de la peau)
- Insulin (niveau d’insuline)
- BMI (indice de masse corporelle)
- DiabetesPedigreeFunction (facteur génétique)
- Age (âge du patient)
- Outcome (variable cible : 0 = non diabétique, 1 = diabétique)

### 🎯 Type de problème
Classification binaire supervisée.

---

## 🔵 2️⃣ Dataset : Diabetes 130-US Hospitals (1999–2008)

Ce dataset contient des informations hospitalières réelles collectées dans 130 hôpitaux aux États-Unis entre 1999 et 2008.

### 📌 Objectif du dataset
Prédire la réadmission hospitalière des patients diabétiques.

### 📊 Types de variables
- Données démographiques (âge, sexe, race)
- Informations d’admission (type d’admission, durée d’hospitalisation)
- Examens médicaux
- Traitements médicamenteux
- Nombre de visites précédentes
- Diagnostics médicaux

### 🎯 Variable cible
readmitted :
- NO → Pas de réadmission
- <30 → Réadmission en moins de 30 jours
- >30 → Réadmission après 30 jours

### 🎯 Type de problème
Classification multi-classes supervisée.

# **==============================================================**
# 🏥 Business Understanding & Data Understanding
# **==============================================================**


# 🔵 1️⃣ Dataset 1 : Détection du Diabète  

## 🎯 Business Objective (BO)

Développer un système capable d’aider au diagnostic précoce du diabète afin d’améliorer la prévention et la prise en charge médicale.

## 🎯 Data Science Objective (DSO)

Construire un modèle de classification supervisée permettant de prédire si un patient est :

- Diabétique (1)
- Non diabétique (0)

Type de problème : **Classification binaire**

---

## 📊 Data Understanding – Analyse Exploratoire (EDA)

Dans cette étape, nous allons :

- Vérifier la structure des données (df.info())
- Identifier les valeurs manquantes
- Étudier la distribution des variables
- Analyser la variable cible (Outcome)
- Visualiser les relations entre les variables
- Utiliser des graphiques :
  - Histogrammes
  - Boxplots
  - Heatmap de corrélation
  - Countplot

L’objectif est de comprendre les données avant la modélisation.

---

# 🔵 2️⃣ Dataset 2 : Réadmission Hospitalière  

## 🎯 Business Objective (BO)

Réduire le taux de réadmission hospitalière des patients diabétiques afin d’améliorer la qualité des soins et réduire les coûts médicaux.

## 🎯 Data Science Objective (DSO)

Construire un modèle capable de prédire la réadmission d’un patient diabétique :

- NO → Pas de réadmission
- <30 → Réadmission en moins de 30 jours
- >30 → Réadmission après 30 jours

Type de problème : **Classification multi-classes supervisée**

---

## 📊 Data Understanding – Analyse Exploratoire (EDA)

Dans cette étape, nous allons :

- Analyser la structure des données (df.info())
- Identifier et traiter les valeurs manquantes
- Étudier la distribution de la variable cible (readmitted)
- Vérifier le déséquilibre des classes
- Analyser les variables importantes :
  - time_in_hospital
  - num_medications
  - number_inpatient
  - age
- Visualiser les relations à l’aide de :
  - Bar plots
  - Countplots
  - Boxplots
  - Heatmap de corrélation

L’objectif est de comprendre les facteurs influençant la réadmission avant la modélisation.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Affichage plus propre des graphiques
plt.style.use("seaborn-v0_8")
sns.set_palette("Set2")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

# 🔹 Réduction de dimension
from sklearn.decomposition import PCA

# 🔹 Clustering (non supervisé)
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN

# 🔹 Modèles supervisés
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import warnings
warnings.filterwarnings("ignore")

from google.colab import files
uploaded = files.upload()

import pandas as pd

df_pima = pd.read_csv("diabetes.csv")

df_hospital = pd.read_csv("diabetic_data.csv")

print("Pima Shape:", df_pima.shape)
print("Hospital Shape:", df_hospital.shape)

"""# 🟢 🔵 DATASET 1 — Détection du Diabète (Pima)"""

df_pima.info()
df_pima.describe()

df_pima.head(10)

(df_pima == 0).sum()

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x="Outcome", data=df_pima)
plt.title("Distribution de la variable cible (Outcome)")
plt.show()

df_pima.hist(figsize=(12,10))
plt.suptitle("Distribution des variables")
plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(df_pima.corr(), annot=True, cmap="coolwarm")
plt.title("Matrice de Corrélation")
plt.show()

"""# 🟢 🔵 DATASET 2 — Réadmission Hospitalière"""

df_hospital.head(10)

df_hospital.info()

df_hospital = df_hospital.replace("?", np.nan)

df_hospital.isnull().sum()

sns.countplot(x="readmitted", data=df_hospital)
plt.title("Distribution de la réadmission")
plt.show()

df_hospital["readmitted"].value_counts(normalize=True)

sns.boxplot(x="readmitted", y="time_in_hospital", data=df_hospital)
plt.title("Temps d'hospitalisation vs Réadmission")
plt.show()

"""# **==============================================================**
# **🟢 🔵 PARTIE DATA PREPARATION**
# **==============================================================**

# 🧹 Data Preparation (Nettoyage et Préparation des Données)

Dans cette étape, nous préparons les données pour les modèles de Machine Learning.

Cette phase est très importante car la qualité des données influence directement la performance du modèle.

Les objectifs de cette étape sont :

- Supprimer les variables inutiles
- Traiter les valeurs manquantes
- Encoder les variables catégorielles
- Normaliser les variables numériques
- Séparer les données en ensemble d'entraînement et de test

À la fin de cette étape, les données seront prêtes pour la modélisation.

# **🟢 🔵 DATASET 1 — PIMA (Détection du Diabète)**
"""

# Remplacer les valeurs 0 non réalistes par NaN
cols_with_zero = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

for col in cols_with_zero:
    df_pima[col] = df_pima[col].replace(0, np.nan)

# Remplir les valeurs manquantes par la médiane
# Pour l'imputation, nous choisissons la médiane (≈125) car :
# 1. Elle est robuste aux valeurs extrêmes (contrairement à la moyenne).
# 2. Elle conserve la distribution générale des données.
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")
df_pima[cols_with_zero] = imputer.fit_transform(df_pima[cols_with_zero])

# Vérification
df_pima.isnull().sum()

"""### 📏 Normalisation des Données

La normalisation est nécessaire pour les modèles sensibles à l'échelle des variables :

- SVM
- KNN
- PCA

Nous utilisons StandardScaler pour mettre toutes les variables sur la même échelle.
"""

from sklearn.preprocessing import StandardScaler

X_pima = df_pima.drop("Outcome", axis=1)
y_pima = df_pima["Outcome"]

scaler = StandardScaler()
X_pima_scaled = scaler.fit_transform(X_pima)

X_train_pima, X_test_pima, y_train_pima, y_test_pima = train_test_split(
    X_pima_scaled, y_pima,
    test_size=0.2,
    random_state=42
)

"""# **🟢 🔵 DATASET 2 — Hospital (Réadmission)**"""

missing_percent = df_hospital.isnull().sum() / len(df_hospital) * 100
missing_percent.sort_values(ascending=False)

cols_to_drop = missing_percent[missing_percent > 80].index

df_hospital.drop(columns=cols_to_drop, inplace=True)

print("Colonnes supprimées :", list(cols_to_drop))
print("Nouvelle dimension :", df_hospital.shape)

df_hospital.drop(columns=["encounter_id", "patient_nbr"],
                 inplace=True,
                 errors="ignore")

print("Dimension après suppression des IDs :", df_hospital.shape)

df_hospital = df_hospital.replace("?", np.nan)

# Remplacer les valeurs manquantes des variables catégorielles
categorical_cols = df_hospital.select_dtypes(include="object").columns

for col in categorical_cols:
    df_hospital[col] = df_hospital[col].fillna("Unknown")

print("Total valeurs manquantes après traitement :")
print(df_hospital.isnull().sum().sum())

"""### 🔄 Encodage des Variables Catégorielles

Les modèles de Machine Learning ne peuvent pas travailler directement avec du texte.

Nous utilisons donc l'encodage One-Hot Encoding pour transformer les variables catégorielles en variables numériques.
"""

X_hospital = df_hospital.drop("readmitted", axis=1)
y_hospital = df_hospital["readmitted"]

X_hospital = pd.get_dummies(X_hospital, drop_first=True)

print("Nombre de colonnes après encodage :", X_hospital.shape[1])

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_hospital_scaled = scaler.fit_transform(X_hospital)

from sklearn.model_selection import train_test_split

X_train_h, X_test_h, y_train_h, y_test_h = train_test_split(
    X_hospital_scaled,
    y_hospital,
    test_size=0.2,
    random_state=42
)

print("Taille Train :", X_train_h.shape)
print("Taille Test :", X_test_h.shape)

"""# **🟢 🔎 Vérification des Données Après Nettoyage**

# 🔎 Vérification des Données Après Nettoyage

Après l’étape de Data Preparation, nous devons vérifier que :

- Les valeurs manquantes ont été traitées
- Les colonnes inutiles ont été supprimées
- Les variables catégorielles ont été encodées
- Les données sont prêtes pour la modélisation

Cette étape permet de s'assurer que le dataset est propre et cohérent avant d’appliquer les modèles de Machine Learning.

# **🟢 🔵 DATASET 1 — Pima (Détection du Diabète)**
"""

df_pima.head(10)

print("Valeurs manquantes :")
print(df_pima.isnull().sum().sum())

df_pima.info()

df_pima.describe()

"""# **🟢 🔵 DATASET 2 — Hospital (Réadmission)**"""

df_hospital.head(10)

print("Valeurs manquantes :")
print(df_hospital.isnull().sum().sum())

print("Nombre de colonnes après encodage :")
print(df_hospital.shape[1])

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x=y_hospital)
plt.title("Distribution de la variable cible - readmitted")
plt.show()

df_hospital["readmitted"].value_counts(normalize=True)

"""# **==============================================================**
# **🟣 PARTIE MODELING**
# **==============================================================**

# 🤖 Modeling

Dans cette étape, nous appliquons plusieurs algorithmes de Machine Learning :

## Modèles non supervisés :
- ACP (PCA)
- K-Means
- DBSCAN

## Modèles supervisés :
- SVM
- KNN
- Arbre de décision
- Régression linéaire

L’objectif est de comparer les performances et analyser les résultats.

# **🟢 🔵 1️⃣ ACP (PCA)**
"""

from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import numpy as np

# ==============================
# 🔹 Encoder la variable cible
# ==============================
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train_h)

# ==============================
# 🔹 PCA pour visualisation 2D
# ==============================
# On garde 2 composantes pour le plot
pca = PCA(n_components=2)

X_train_pca = pca.fit_transform(X_train_h)
X_test_pca = pca.transform(X_test_h)

print("Variance expliquée :", pca.explained_variance_ratio_)
print("Variance totale expliquée :",
      np.sum(pca.explained_variance_ratio_))

# ==============================
# 🔹 Visualisation
# ==============================
plt.figure(figsize=(8,6))

scatter = plt.scatter(
    X_train_pca[:,0],
    X_train_pca[:,1],
    c=y_train_encoded,
    cmap='viridis',
    alpha=0.6
)

plt.colorbar(scatter, label="Classes (Encodées)")
plt.title("ACP - Projection 2D")
plt.xlabel("Composante Principale 1")
plt.ylabel("Composante Principale 2")
plt.show()

"""# **🟢 🔵 2️⃣ K-Means**"""

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

# Réduction à 2 dimensions pour visualisation
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_hospital_scaled)

# KMeans
kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(X_pca)

# Visualisation
plt.figure(figsize=(8,6))
sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=clusters, palette="Set1")
plt.title("K-Means Clustering (PCA Reduced Data)")
plt.show()

"""# **🟢 🔵 3️⃣ DBSCAN**"""

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=0.5, min_samples=5)
db_labels = dbscan.fit_predict(X_train_pca)

plt.figure(figsize=(8,6))
sns.scatterplot(
    x=X_train_pca[:,0],
    y=X_train_pca[:,1],
    hue=db_labels,
    palette="Set1"
)
plt.title("DBSCAN Clustering")
plt.show()

"""# **🟢 🔵 4️⃣ SVM**"""

from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd

# ⚠️ Échantillon pour accélérer l'exécution
df_sample = df_hospital.sample(10000, random_state=42)

# Séparer features et target
X_h = df_sample.drop("readmitted", axis=1)
y_h = df_sample["readmitted"]

# Encoder les variables catégorielles (texte)
X_h_encoded = pd.get_dummies(X_h, drop_first=True)

# Normalisation
scaler = StandardScaler()
X_h_scaled = scaler.fit_transform(X_h_encoded)

# Split train/test
X_train_h, X_test_h, y_train_h, y_test_h = train_test_split(
    X_h_scaled, y_h, test_size=0.2, random_state=42
)

# ✅ SVM avec kernel linéaire
svm = SVC(kernel="linear", max_iter=2000)
svm.fit(X_train_h, y_train_h)

# Prédictions
y_pred_svm = svm.predict(X_test_h)

# Évaluation
print("Accuracy SVM :", accuracy_score(y_test_h, y_pred_svm))

# Matrice de confusion
cm = confusion_matrix(y_test_h, y_pred_svm)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix - SVM (kernel linéaire)")
plt.show()

"""# **🟢 🔵 5️⃣ KNN**"""

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_h, y_train_h)

y_pred_knn = knn.predict(X_test_h)

print("Accuracy KNN :", accuracy_score(y_test_h, y_pred_knn))

cm = confusion_matrix(y_test_h, y_pred_knn)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Greens")
plt.title("Confusion Matrix - KNN")
plt.show()

"""# **🟢 🔵 6️⃣ Arbre de Décision**"""

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train_h, y_train_h)

y_pred_dt = dt.predict(X_test_h)

print("Accuracy Decision Tree :", accuracy_score(y_test_h, y_pred_dt))

cm = confusion_matrix(y_test_h, y_pred_dt)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Oranges")
plt.title("Confusion Matrix - Decision Tree")
plt.show()

"""# **🟢 🔵 7️⃣ Régression Linéaire**"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

y_train_h_enc = y_train_h.replace({"NO":0, ">30":1, "<30":2})
y_test_h_enc = y_test_h.replace({"NO":0, ">30":1, "<30":2})

# Régression linéaire
lr = LinearRegression()
lr.fit(X_train_h, y_train_h_enc)

# Prédictions
y_pred_lr = lr.predict(X_test_h)

# Arrondir les prédictions pour obtenir des classes
y_pred_lr_classes = y_pred_lr.round().astype(int)

# Évaluation
print("Accuracy Régression Linéaire :", accuracy_score(y_test_h_enc, y_pred_lr_classes))
print("MSE :", mean_squared_error(y_test_h_enc, y_pred_lr))
print("R² Score :", r2_score(y_test_h_enc, y_pred_lr))

# Matrice de confusion
cm = confusion_matrix(y_test_h_enc, y_pred_lr_classes)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Purples")
plt.title("Confusion Matrix - Régression Linéaire")
plt.show()

"""# **============================================================**
# **📊 PARTIE ÉVALUATION**
# **============================================================**

# 📊 Évaluation des Modèles

Dans cette étape, nous comparons les performances des trois modèles supervisés :

- SVM
- KNN
- Arbre de Décision

La comparaison est basée sur les métriques suivantes :

- Accuracy
- Precision
- Recall
- F1-Score
- Matrice de confusion

L’objectif est d’identifier le modèle le plus performant pour notre problème médical.
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Fonction pour afficher les métriques
def evaluate_model(name, y_true, y_pred):
    print("==========", name, "==========")
    print("Accuracy :", accuracy_score(y_true, y_pred))
    print("Precision:", precision_score(y_true, y_pred, average='weighted'))
    print("Recall   :", recall_score(y_true, y_pred, average='weighted'))
    print("F1-Score :", f1_score(y_true, y_pred, average='weighted'))
    print("\n")

# Évaluation des 4 modèles
evaluate_model("SVM", y_test_h, y_pred_svm)
evaluate_model("KNN", y_test_h, y_pred_knn)
evaluate_model("Decision Tree", y_test_h, y_pred_dt)
evaluate_model("Linear Regression", y_test_h_enc, y_pred_lr_classes)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Fonction pour calculer les métriques
def get_metrics(y_true, y_pred):
    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, average='weighted'),
        "Recall": recall_score(y_true, y_pred, average='weighted'),
        "F1-Score": f1_score(y_true, y_pred, average='weighted')
    }

# ⚠️ Pour la régression linéaire, utiliser les cibles encodées et les prédictions arrondies
# Exemple :
# y_pred_lr_classes = y_pred_lr.round().astype(int)

# Collecte des résultats
results = pd.DataFrame([
    {"Model": "SVM", **get_metrics(y_test_h, y_pred_svm)},
    {"Model": "KNN", **get_metrics(y_test_h, y_pred_knn)},
    {"Model": "Decision Tree", **get_metrics(y_test_h, y_pred_dt)},
    {"Model": "Linear Regression", **get_metrics(y_test_h_enc, y_pred_lr_classes)}
])

print(results)

# 🔹 Visualisation Accuracy
plt.figure(figsize=(8,5))
sns.barplot(x="Model", y="Accuracy", data=results)
plt.title("Comparaison des Accuracy")
plt.ylim(0,1)
plt.show()

# 🔹 Visualisation F1-Score (optionnel mais utile)
plt.figure(figsize=(8,5))
sns.barplot(x="Model", y="F1-Score", data=results)
plt.title("Comparaison des F1-Score")
plt.ylim(0,1)
plt.show()

"""
# 🏁 Conclusion Générale du Projet

Ce projet de Machine Learning a été réalisé en suivant une méthodologie structurée :

## 1️⃣ Business Understanding
Nous avons défini deux objectifs principaux :

- 🔵 Dataset 1 : Détection du diabète (problème de classification binaire).
- 🔵 Dataset 2 : Prédiction de la réadmission hospitalière (problème de classification multi-classes).

Les objectifs ont été fixés dès le début et ne peuvent plus être modifiés.

---

## 2️⃣ Data Understanding
Une analyse exploratoire (EDA) a été réalisée afin de :

- Comprendre la structure des données
- Identifier les valeurs manquantes
- Étudier la distribution des variables
- Analyser la variable cible
- Visualiser les relations entre les variables

Cette étape nous a permis de mieux comprendre les caractéristiques des datasets avant la modélisation.

---

## 3️⃣ Data Preparation
Les données ont été nettoyées et préparées :

- Suppression des variables inutiles
- Traitement des valeurs manquantes
- Suppression des colonnes avec plus de 80% de valeurs manquantes
- Encodage des variables catégorielles
- Normalisation des données
- Séparation en ensemble d'entraînement et de test

Les données sont maintenant prêtes pour la modélisation.

---

## 4️⃣ Modeling
Plusieurs modèles ont été appliqués :

### 🔹 Modèles non supervisés :
- ACP (PCA)
- K-Means
- DBSCAN

### 🔹 Modèles supervisés :
- SVM
- KNN
- Arbre de Décision
- Régression Linéaire

Ces modèles ont permis d’analyser les données sous différents angles.

---

## 5️⃣ Évaluation et Comparaison

Les performances des modèles supervisés ont été comparées à l’aide de :

- Accuracy
- Precision
- Recall
- F1-Score
- Matrice de confusion

La comparaison a permis d’identifier le modèle le plus performant pour notre problème.

Dans un contexte médical, le F1-Score et le Recall sont particulièrement importants afin de minimiser les erreurs de classification.

---

## 🎯 Conclusion Finale

Ce projet démontre l’application complète d’un pipeline de Machine Learning :

Business Understanding → Data Understanding → Data Preparation → Modeling → Evaluation.

Les résultats obtenus montrent que les modèles de classification supervisée permettent de prédire efficacement :

- La présence du diabète
- La réadmission hospitalière

Ce travail constitue une base solide pour des améliorations futures, telles que l’optimisation des hyperparamètres et l’utilisation de techniques avancées.
"""